In [1]:
import numpy as np

In [14]:
def possible(y,x,n):
    global grid
    # n is the number we want to fill in
    N = len(grid)
    # 1st 
    # check if n already existed in vertical (y) axis
    # if exists, return False (not possible)
    for i in range(N):
        if grid[y][i] == n:
            return False

    # 2nd
    # check horizontal (x) axis
    for i in range(N):
        if grid[i][x] == n:
            return False

    # 3rd
    # check if it points to anything
    if x > 0:
        if grid[y][x - 1] != 0:
            y0 = grid[y][x - 1] - 1
            x0 = n-1
            print(grid[y0][x0], y+1)
            if grid[y0][x0] not in [0, y+1]:
                return False
    elif x < N-1:
        if grid[y][x + 1] != 0:
            y0 = n-1
            x0 = grid[y][x + 1] - 1
            print(grid[y0][x0], y+1)
            if grid[y0][x0] not in [0, y + 1]:
                return False

    # return true if pass all 3 checks.
    return True

In [15]:
def solve(iter = 0):
  global grid
  #if iter > 1000:
  #  print(f"exiting after {iter} iterations")
  #  return grid
  N = len(grid)
  for y in range(N):
    for x in range(N):
      #print(f'iter: {iter}, y: {y}, x: {x}, grid: {grid[y][x]}')
      # Find blank positions in the grid (value = 0)
      if grid[y][x] == 0:
        # Loop n from 1-8
        for n in range(1, N + 1):
          if possible(y, x, n):
            grid[y][x] = n
            solve(iter + 1)

            # This is where backtracking happens
            # Reset the latest position back to 0 and try with new n value
            grid[y][x] = 0
        return
  print(np.matrix(grid))
  input('More?')

In [16]:
size = 8
grid = np.zeros((size,size), dtype=int)
for i in range(size-2):
    grid[i][i+1]=size
grid[len(grid)-1,len(grid)//2 - 1] = 1
#grid = np.matrix(grid)
grid[-1] = [5,6,7,1,2,3,4,0]
grid[0,2] = 4
grid[1,3] = 5
grid[2,4] = 6
grid[3,5] = 7
grid[4,6] = 1
grid[0] = [3,8,4,2,1,5,7,6]
grid[1] = [1,4,8,5,3,2,6,7]
grid[2] = [7,2,5,8,6,4,3,1]
grid[3] = [4,1,3,6,8,7,5,2]
grid[4] = [6,5,2,4,7,8,1,3]
grid

array([[3, 8, 4, 2, 1, 5, 7, 6],
       [1, 4, 8, 5, 3, 2, 6, 7],
       [7, 2, 5, 8, 6, 4, 3, 1],
       [4, 1, 3, 6, 8, 7, 5, 2],
       [6, 5, 2, 4, 7, 8, 1, 3],
       [0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [5, 6, 7, 1, 2, 3, 4, 0]])

In [17]:
solve()

8 6
6 6
0 6
4 6
0 6
6 6
8 6
6 6
6 6
1 6


In [6]:
grid

array([[3, 8, 4, 2, 1, 5, 7, 6],
       [1, 4, 8, 5, 3, 2, 6, 7],
       [7, 2, 5, 8, 6, 4, 3, 1],
       [4, 1, 3, 6, 8, 7, 5, 2],
       [6, 5, 2, 4, 7, 8, 1, 3],
       [0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [5, 6, 7, 1, 2, 3, 4, 0]])

In [10]:
from random import sample

In [13]:
grid = [
    [3,8,4,2,1,5,7,6],
    [1,4,8,5,3,2,6,7],
    [7,2,5,8,6,4,3,1],
    [4,1,3,6,8,7,5,2],
    [6,5,2,4,7,8,1,3],
    [2,7,6,3,5,1,8,4],
    [8,3,1,7,4,6,2,5],
    [5,6,7,1,2,3,4,8]]

for _ in range(5):
    x,y = sample(range(8), 2)
    grid[x][y] = 0
    #print(x,y)
grid

[[3, 8, 4, 2, 1, 5, 7, 6],
 [0, 4, 8, 5, 3, 2, 6, 7],
 [7, 2, 5, 8, 6, 4, 3, 1],
 [0, 1, 3, 6, 8, 7, 5, 2],
 [6, 5, 2, 0, 7, 8, 1, 3],
 [0, 7, 6, 3, 5, 1, 8, 4],
 [0, 3, 1, 7, 4, 6, 2, 5],
 [5, 6, 7, 1, 2, 3, 4, 8]]

In [14]:
solve()

[[3 8 4 2 1 5 7 6]
 [1 4 8 5 3 2 6 7]
 [7 2 5 8 6 4 3 1]
 [4 1 3 6 8 7 5 2]
 [6 5 2 4 7 8 1 3]
 [2 7 6 3 5 1 8 4]
 [8 3 1 7 4 6 2 5]
 [5 6 7 1 2 3 4 8]]
